baseURL: http://ivanruvalcaba.cf/
title: Bitácora de Iván Ruvalcaba
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

params:
  ShowPostNavLinks: true
  ShowReadingTime: true

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: Archivo
      url: archives
      weight: 5

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
