baseURL: "http://ivanruvalcaba.cf/"
title: "$ cat /dev/random > /dev/null 2>&1"
languageCode: es-MX
defaultContentLanguage: es
paginate: 5
theme: PaperMod

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true
metaDataFormat: "yaml"

params:
  author: Iván Ruvalcaba
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
  analytics.bing.SiteVerificationTag: "923F21AF4644A4341700A61DB79C740E"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  profileMode:
    enabled: true
    title: Iván Ruvalcaba
    subtitle: Artesano de Software, Blogger e Hipster 💻
    imageUrl: "avatar-180x180.png"
    imageTitle: Iván Ruvalcaba
  socialIcons:
    - name: rss
      url: "index.xml"
    - name: twitter
      url: "https://twitter.com/ivnruvalcaba"
    - name: email
      url: "mailto:ivanruvalcaba@disroot.org"
    - name: gitlab
      url: "https://gitlab.com/ivanruvalcaba"
    - name: github
      url: "https://github.com/ivanruvalcaba"
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowShareButtons: true

menu:
  main:
    - name: Blog
      url: post
      weight: 1
    - name: Archivo
      url: archives
      weight: 5
    - name: Buscar
      url: search
      weight: 10
    - name: Acerca de
      url: acerca-de
      weight: 15

outputs:
  home:
    - HTML
    - JSON
    - RSS

taxonomies:
  category: categories
  tag: tags
  series: series

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

# Los siguientes parámetros de configuración corresponden a la las regulaciones
# solicitadas por la «General Data Protection Regulation (GDPR)».
#
# Para mayor información, véase: https://gohugo.io/about/hugo-and-gdpr/
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
